### ISSUE TITLE
ERROR: Could not attach to process.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [patric-r/jvmtop#24]
```
 JvmTop 0.6.0 alpha          amd64,  4 cpus, Linux 2.6.18-19
 http://code.google.com/p/jvmtop

ERROR: Could not attach to process.


java -version
java version "1.6.0_22"
Java(TM) SE Runtime Environment (build 1.6.0_22-b04)
Java HotSpot(TM) 64-Bit Server VM (build 17.1-b03, mixed mode)


```

Original issue reported on code.google.com by `BM888...@gmail.com` on 12 Jul 2013 at 3:58

**Comment by patric-r** [comment]
Unfortunately, some JVMs do not allow monitoring from any other user than the owning user (this includes root). This is built-in security check in the jvm, which jvmtop cannot override.

I've updated the [FAQ](https://github.com/patric-r/jvmtop/blob/master/doc/FAQ.md).
