### ISSUE TITLE
empty console on Mac (OS X 10.9.5)

### ISSUE THREAD

**Issue by salilk** [patric-r/jvmtop#64]
Hi,

I've downloaded the gzip file and running ./jvmtop.sh but its showing me nothing. Not sure what is it? any errors?

**Comment by patric-r** [comment]
Hi,
what happens if you execute:
bash -x ./jvmtop.sh

instead? If there's some output, please paste it here.

**Comment by salilk** [comment]
thanks Patric.. Here you go!
==========================================
 JvmTop 0.8.0 alpha - 14:53:26, x86_64,  4 cpus, Mac OS X 10.9.5, load avg 2.33
 http://code.google.com/p/jvmtop

  PID MAIN-CLASS      HPCUR HPMAX NHCUR NHMAX    CPU     GC    VM USERNAME   #T DL
 1490 .druid.cli.Main  136m  227m   52m  130m 17.97%  0.26% O7U79   salilk  205   
  292                  219m  725m  214m  575m  2.47%  0.00% O7U79   salilk   53   
 5143 m.jvmtop.JvmTop   56m  910m    9m  560m  0.89%  0.00% O7U79   salilk   20   
 5031 moteMavenServer   29m  455m   16m  130m  0.42%  0.00% O7U79   salilk   14   
 1460 kafka.Kafka     [ERROR: Connection refused/access denied] 
 1453 .QuorumPeerMain [ERROR: Connection refused/access denied] 
==========================================

**Comment by patric-r** [comment]
It seems that jvmtop is now working perfectly. Do you get the same output when invoking jvmtop.sh without bash -x ?

**Comment by salilk** [comment]
interesting - yes it's working fine now. But what was it? What should I do, if this happens again (other than restarting my machine) :-)
