### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: com/jvmtop/JvmTop

### ISSUE THREAD

**Issue by tduraipkt** [patric-r/jvmtop#68]
Similar issue posted here
https://github.com/patric-r/jvmtop/issues/63

jvmtop.jar is missing in the extracted zip file "jvmtop-master.zip".

**Comment by patric-r** [comment]
Most probably you clicked on "download zip" on the right.
This is the github source code export functionality.

To download the official jvmtop release, please use the [releases tab](https://github.com/patric-r/jvmtop/releases).
Please let me know if this worked for you.

**Comment by tduraipkt** [comment]
Thank you Patric now I could see that jar. But executing that script throws access denied exception. I'll post the detail in a different thread.

**Comment by patric-r** [comment]
Thank you for your confirmation.
Yes, please just open another thread, I'll have a look.
