### ISSUE TITLE
Add install instructions to the readme

### ISSUE THREAD

**Issue by xenoterracide** [patric-r/jvmtop#69]
just discovered this project, and I'm trying to figure out how to get started and what the preferred path to installation is. is there a downloadable jar? or do I have to build it myself?

**Comment by patric-r** [comment]
Hi,
thanks for your suggestion.
The installation is quite easy: Just click on the [Releases tab](https://github.com/patric-r/jvmtop/releases), download the most recent tar.gz, extract it on your machine and run ```jvmtop.sh``` (linux/unix) or ```jvmtop.bat``` (windows).

I'll think about improving the documentation. Suggestions are very welcome.

**Comment by xenoterracide** [comment]
I doubt it needs to be much more than that. Honestly the "releases" tab is less obvious on github since they moved to pure iconifry, and most thing I install with Java are on maven central. honestly I'm not actually sure how to navigate to the releases tab, so thanks for the link.

**Comment by bradparks** [comment]
yeah i agree - i think all you need to do is add "Download the latest release here, then run jvmtop.sh" to your readme, and you're good. I just downloaded it and thought I had to build it. I built it but wasn't sure how to run it and was about to add an issue myself for this, so same prob here ;-) Thanks!

**Comment by patric-r** [comment]
Good point, changed it accordingly.
Thank you.
