### ISSUE TITLE
Explanation of values shown in the second para

### ISSUE THREAD

**Issue by mskadu** [patric-r/jvmtop#71]
Hello,

I was wondering if you could help me figure out an explanation for columns in the following lines displayed during the detailed / single VM monitoring mode?

<pre><code> UP: 869:33m #THR: 106  #THRPEAK: 143  #THRCREATED: 128020 USER: webserver
 CPU:  4.55% GC:  3.25% HEAP: 137m / 227m NONHEAP:  75m / 304m
</code></pre>

My guesses for each of those headings in caps. Would be great if you could confirm/ correct
``UP`` -- ??
``THR`` -- Number of Open Threads?
``#THRPEAK`` -- Peak Number of Threads that were opened?
``#THRCREATED`` -- ??
``USER`` -- User the VM is executing as
``CPU`` -- %CPU in use
``GC`` -- Amount of memory freed/ GC-ed? Pending GC?
``HEAP`` -- Amount of Heap memory / Max?
``NONHEAP`` -- Amount of Heap Memory/ Max?

Thanks.

**Comment by mskadu** [comment]
Based from your own source my best guesses 
``UP`` -- <pre><code>vmInfo_.getRuntimeMXBean().getUptime()</code></pre> How long the JVM has been running
THR -- <pre><code>vmInfo_.getThreadCount()</code></pre> current thread count
#THRPEAK -- <pre><code>vmInfo_.getThreadMXBean().getPeakThreadCount()</code></pre> Peak Thread Count (during the Up time of this JVM?)
#THRCREATED -- <pre><code>vmInfo_.getThreadMXBean().getTotalStartedThreadCount()</code></pre> Total Started Thread Count? (is this a cumulative figure of total threads started?)
USER -- OS User the VM is executing as
CPU -- %CPU in use
GC -- <pre><code>vmInfo_.getGcLoad()</code></pre> (still not clear)
HEAP -- <pre><code>vmInfo_.getHeapUsed()</code></pre> / <pre><code>vmInfo_.getHeapMax()</code></pre> (Heap Mem Used/ Max Heap Mem Used)
NONHEAP -- <pre><code>vmInfo_.getNonHeapUsed()</code></pre> / <pre><code>vmInfo_.getNonHeapMax()</code></pre> (non-Heap Mem Used/ non-Heap Mem Max)

Any chance you can provide info/ correct on the ones I missed above?

Thanks.

**Comment by patric-r** [comment]
I'm sorry for the delay. 

Have you had a look at [this wiki page](https://github.com/patric-r/jvmtop/blob/master/doc/ExampleOutput.md)?

If things are still unclear, please let me know, I'll try to improve the documentation.
Thank you.
