### ISSUE TITLE
old website is noted in jvmtop command

### ISSUE THREAD

**Issue by jhelfman** [patric-r/jvmtop#76]
JvmTop 0.8.0 alpha - 13:19:04,  amd64,  2 cpus, FreeBSD 10.2-RE, load avg 0.23
 http://code.google.com/p/jvmtop

Attached patch.

[jvmtop.patch.txt](https://github.com/patric-r/jvmtop/files/102039/jvmtop.patch.txt)

**Comment by patric-r** [comment]
Thanks for the patch - this has already been changed and will be included in the next release:
https://github.com/patric-r/jvmtop/commit/cb3789e22dc45e3a1bdc42ef9bd253af35455cef
