### ISSUE TITLE
Can't find jvptop.sh file

### ISSUE THREAD

**Issue by mikehomee** [patric-r/jvmtop#77]
Can't find jvptop.sh file

**Comment by patric-r** [comment]
Did you download [https://github.com/patric-r/jvmtop/releases/download/0.8.0/jvmtop-0.8.0.tar.gz](https://github.com/patric-r/jvmtop/releases/download/0.8.0/jvmtop-0.8.0.tar.gz) (see 'releases' tab)?

**Comment by mikehomee** [comment]
Sorry, i used git clone.
Thanks for the url. 
after running the script, i have new error
/usr/lib/jvm/java-7-oracle/jre seems to be no JDK!

Thank you!

**Comment by patric-r** [comment]
jvmtop requires a JDK (a JRE is not sufficient). If /usr/lib/jvm/java-7-oracle contains a JDK, please set `JAVA_HOME` environment variable to `/usr/lib/jvm/java-7-oracle`.

See also [https://github.com/patric-r/jvmtop/blob/master/INSTALL](https://github.com/patric-r/jvmtop/blob/master/INSTALL)

**Comment by mikehomee** [comment]
Perfect!
I thought my java env was already set since I can run java commands perfectly. 
After setting up JAVA_HOME, the script is running!

Thank you so much!

PS. I'm sorry for being lazy for not reading the important notes.

**Comment by patric-r** [comment]
You're welcome.
