### ISSUE TITLE
Cant run JVM top on Windows 

### ISSUE THREAD

**Issue by Veeradas** [patric-r/jvmtop#81]
As mentioned in the installation guide downloaded jvmtop-0.8.0.tar.gz and extracted the local folder C:\Downloads\jvmtop-0.8.0  . Also setup the Java_home version JDK1.6.0_11. Then opened command prompt and navigated to the extracted JVMtop folder  C:\Downloads\jvmtop-0.8.0 and executed the jvmtop.bat file and found following error.

C:\Downloads\jvmtop-0.8.0>jvmtop.bat
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

**Comment by patric-r** [comment]
Thank you for the report.
Would you please try exchanging the jvmtop.bat file with [the one in the git repository ](https://raw.githubusercontent.com/patric-r/jvmtop/master/src/main/wrappers/jvmtop.bat) to see if this will fix your problem?

**Comment by Veeradas** [comment]
Thank for your response.  It is keep on prompting following results.  I think it supposed to show all the PID and their usage details







 JvmTop 0.8.0 alpha - 10:27:28,  amd64,  4 cpus, Windows Vista 6
 http://code.google.com/p/jvmtop

  PID MAIN-CLASS      HPCUR HPMAX NHCUR NHMAX    CPU     GC    VM USERNAME   #T
DL
 6004 m.jvmtop.JvmTop   20m  883m   10m  132m  0.74%  0.81% S6U11 veeradas   12
































 JvmTop 0.8.0 alpha - 10:27:29,  amd64,  4 cpus, Windows Vista 6
 http://code.google.com/p/jvmtop

  PID MAIN-CLASS      HPCUR HPMAX NHCUR NHMAX    CPU     GC    VM USERNAME   #T
DL
 6004 m.jvmtop.JvmTop    3m  883m   10m  132m  0.75%  0.00% S6U11 veeradas   12
































 JvmTop 0.8.0 alpha - 10:27:30,  amd64,  4 cpus, Windows Vista 6
 http://code.google.com/p/jvmtop

  PID MAIN-CLASS      HPCUR HPMAX NHCUR NHMAX    CPU     GC    VM USERNAME   #T
DL
 6004 m.jvmtop.JvmTop    5m  883m   10m  132m  1.11%  0.00% S6U11 veeradas   12
































 JvmTop 0.8.0 alpha - 10:27:31,  amd64,  4 cpus, Windows Vista 6
 http://code.google.com/p/jvmtop

  PID MAIN-CLASS      HPCUR HPMAX NHCUR NHMAX    CPU     GC    VM USERNAME   #T
DL
 6004 m.jvmtop.JvmTop    7m  883m   10m  132m  0.36%  0.00% S6U11 veeradas   12
































 JvmTop 0.8.0 alpha - 10:27:32,  amd64,  4 cpus, Windows Vista 6
 http://code.google.com/p/jvmtop

  PID MAIN-CLASS      HPCUR HPMAX NHCUR NHMAX    CPU     GC    VM USERNAME   #T
DL
 6004 m.jvmtop.JvmTop    9m  883m   10m  132m  0.75%  0.00% S6U11 veeradas   12
































 JvmTop 0.8.0 alpha - 10:27:33,  amd64,  4 cpus, Windows Vista 6
 http://code.google.com/p/jvmtop

  PID MAIN-CLASS      HPCUR HPMAX NHCUR NHMAX    CPU     GC    VM USERNAME   #T
DL
 6004 m.jvmtop.JvmTop   11m  883m   10m  132m  1.11%  0.00% S6U11 veeradas   12
































 JvmTop 0.8.0 alpha - 10:27:34,  amd64,  4 cpus, Windows Vista 6
 http://code.google.com/p/jvmtop

  PID MAIN-CLASS      HPCUR HPMAX NHCUR NHMAX    CPU     GC    VM USERNAME   #T
DL
 6004 m.jvmtop.JvmTop   13m  883m   10m  132m  0.37%  0.00% S6U11 veeradas   12
































 JvmTop 0.8.0 alpha - 10:27:36,  amd64,  4 cpus, Windows Vista 6
 http://code.google.com/p/jvmtop

  PID MAIN-CLASS      HPCUR HPMAX NHCUR NHMAX    CPU     GC    VM USERNAME   #T
DL
 6004 m.jvmtop.JvmTop   15m  883m   10m  132m  0.75%  0.00% S6U11 veeradas   12

Terminate batch job (Y/N)? y

C:\Downloads\jvmtop-0.8.0 >

**Comment by patric-r** [comment]
it seem to work now, that's the regular "overview mode".
Only one more thing bothers me:
Does it clear its screen after each update (like you can see it [here](https://github.com/patric-r/jvmtop/blob/master/doc/ExampleOutput.md) does it print the lines after the previous ones so that the screen gets filled up or even scrolls?

**Comment by Veeradas** [comment]
it is working now
